#!/usr/bin/env node
const _ = require("lodash")
const fs = require("fs")
const path = require("path")
const program = require("commander")

program
  .version('0.0.1')

program
    .command('build')
    .description('build')
    .action((env, options) => {
        let config = require("../config.js")
        const intents = config.intents.map((i) => _.pick(i, "name", "samples", "slots"))
        let model = require("../models/en-US.base.json")
        model.interactionModel.languageModel.intents = model.interactionModel.languageModel.intents.concat(intents)
        let modelJSON = JSON.stringify(model, null, 2)
        fs.writeFileSync(path.resolve(__dirname, "../models/en-US.json"), modelJSON)

        fs.copyFileSync(path.resolve(__dirname, "../config.js"), path.resolve(__dirname, "../lambda/custom/config.js"))
    });

program.parse(process.argv);    

  